### ISSUE TITLE
Hey bud!

### ISSUE THREAD

**Issue by voept** [vibedivide/sploit#1]
Hey man, hope you're having a great day! I really don't appreciate the racism and/or the DDoSing my chatbox, and the spam pinging, and telling others to label me as a "skid." It's not cool man.

  - Thanks, Outersloth!

**Comment by vibedivide** [comment]
xd

**Comment by vibedivide** [comment]
skiddy skid skid clacking away

**Comment by vibedivide** [comment]
ur chatbox was ass anyway
